services:
    avathar.badge.listener:
        class: avathar\badge\event\listener
        arguments:
            - '%core.root_path%ext/avathar/badge/'
            - '@template'
        tags:
            - { name: event.listener }
